# to get values like this, run !uni <emoji> while the bot is active
UNICODE_FORWARD_ARROW = "\N{BLACK RIGHT-POINTING TRIANGLE}"

START_GAME_EMOJI = UNICODE_FORWARD_ARROW


# Except for these numbers because it just lies about them.
# Turns out, the entire discord library is weird about sending the number emoji
UNICODE_0 = "0\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_1 = "1\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_2 = "2\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_3 = "3\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_4 = "4\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_5 = "5\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_6 = "6\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_7 = "7\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_8 = "8\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_9 = "9\N{VARIATION SELECTOR-16}\N{COMBINING ENCLOSING KEYCAP}"
