# to get values like this, run !uni <emoji> while the bot is active
UNICODE_FORWARD_ARROW = "\N{BLACK RIGHT-POINTING TRIANGLE}"




# except for these numbers because it just lies about them for some reason
UNICODE_1 = "1\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_2 = "2\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_3 = "3\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_4 = "4\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_5 = "5\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_6 = "6\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_7 = "7\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_8 = "8\N{COMBINING ENCLOSING KEYCAP}"
UNICODE_9 = "9\N{COMBINING ENCLOSING KEYCAP}"
